"""Initial migration

Revision ID: 453d43c92c9f
Revises: 
Create Date: 2023-07-30 15:42:54.059312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453d43c92c9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('avatar', sa.String(length=60), server_default='default-bear.svg', nullable=False),
    sa.Column('location', sa.String(length=60), nullable=True),
    sa.Column('blurb', sa.String(length=280), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
